### ISSUE TITLE
Also add label for released PRs

### ISSUE THREAD

**Issue by TravisEz13** [rdlf0/comment-released-prs-action#13]
Add a feature to label PRs with the release(s) that they were released in.  There should be a template but the default could just but a tag, but an alternative maybe `release-<tag>`

**Comment by rdlf0** [comment]
Thank you for the suggestion @TravisEz13! I will definitely put it in the backlog and you will see it live soon!

**Comment by TravisEz13** [comment]
Thanks!

**Comment by TravisEz13** [comment]
I think for our purposes, we would need to change how you get the list of PRs.  We cherry pick PRs into old releases.  We currently parse our release notes to get the list of PRs.  I might fork and do that if you aren't interested in that.  We provide a regex and matching group as a parameter.  Since our change logs our auto-generated, this provides consistent results.

**Comment by TravisEz13** [comment]
I'd of course be willing to contribute back.

**Comment by rdlf0** [comment]
Yeah, I'm trying to keep this action generic, so it relies only on what GitHub provides. Adding a 3rd party dependency would make it case-specific, which I'm trying to avoid for now. Of course, I'm open to discussing any ideas and potential implementations.
